/* JS */ gapi.loaded_0(function(_){var window=this;
var da,ka,va,ya,Aa;_.ca=function(a){return function(){return _.ba[a].apply(this,arguments)}};_._DumpException=function(a){throw a;};_.ba=[];da=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};_.ea=function(a){var b="undefined"!=typeof window.Symbol&&window.Symbol.iterator&&a[window.Symbol.iterator];return b?b.call(a):{next:da(a)}};_.ha="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b};
if("function"==typeof Object.setPrototypeOf)ka=Object.setPrototypeOf;else{var la;a:{var oa={a:!0},pa={};try{pa.__proto__=oa;la=pa.a;break a}catch(a){}la=!1}ka=la?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}_.sa=ka;va="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};
ya="undefined"!=typeof window&&window===this?this:"undefined"!=typeof window.global&&null!=window.global?window.global:this;Aa=function(a,b){if(b){var c=ya;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&va(c,a,{configurable:!0,writable:!0,value:b})}};
Aa("Array.prototype.find",function(a){return a?a:function(a,c){a:{var b=this;b instanceof String&&(b=String(b));for(var e=b.length,f=0;f<e;f++){var h=b[f];if(a.call(c,h,f,b)){a=h;break a}}a=void 0}return a}});
var Ba=function(){Ba=function(){};ya.Symbol||(ya.Symbol=Da)},Da=function(){var a=0;return function(b){return"jscomp_symbol_"+(b||"")+a++}}(),Fa=function(){Ba();var a=ya.Symbol.iterator;a||(a=ya.Symbol.iterator=ya.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&va(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return Ea(da(this))}});Fa=function(){}},Ea=function(a){Fa();a={next:a};a[ya.Symbol.iterator]=function(){return this};return a},Ha=function(a,b){return Object.prototype.hasOwnProperty.call(a,
b)};
Aa("WeakMap",function(a){function b(){}function c(a){Ha(a,e)||va(a,e,{value:new b})}function d(a){var d=Object[a];d&&(Object[a]=function(a){if(a instanceof b)return a;c(a);return d(a)})}if(function(){if(!a||!Object.seal)return!1;try{var b=Object.seal({}),c=Object.seal({}),d=new a([[b,2],[c,3]]);if(2!=d.get(b)||3!=d.get(c))return!1;d["delete"](b);d.set(c,4);return!d.has(b)&&4==d.get(c)}catch(p){return!1}}())return a;var e="$jscomp_hidden_"+Math.random();d("freeze");d("preventExtensions");d("seal");var f=
0,h=function(a){this.Aa=(f+=Math.random()+1).toString();if(a){a=_.ea(a);for(var b;!(b=a.next()).done;)b=b.value,this.set(b[0],b[1])}};h.prototype.set=function(a,b){c(a);if(!Ha(a,e))throw Error("a`"+a);a[e][this.Aa]=b;return this};h.prototype.get=function(a){return Ha(a,e)?a[e][this.Aa]:void 0};h.prototype.has=function(a){return Ha(a,e)&&Ha(a[e],this.Aa)};h.prototype["delete"]=function(a){return Ha(a,e)&&Ha(a[e],this.Aa)?delete a[e][this.Aa]:!1};return h});
Aa("Map",function(a){if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var b=Object.seal({x:4}),c=new a(_.ea([[b,"s"]]));if("s"!=c.get(b)||1!=c.size||c.get({x:4})||c.set({x:4},"t")!=c||2!=c.size)return!1;var d=c.entries(),e=d.next();if(e.done||e.value[0]!=b||"s"!=e.value[1])return!1;e=d.next();return e.done||4!=e.value[0].x||"t"!=e.value[1]||!d.next().done?!1:!0}catch(q){return!1}}())return a;Fa();var b=new window.WeakMap,c=function(a){this.uf=
{};this.Ye=f();this.size=0;if(a){a=_.ea(a);for(var b;!(b=a.next()).done;)b=b.value,this.set(b[0],b[1])}};c.prototype.set=function(a,b){a=0===a?0:a;var c=d(this,a);c.list||(c.list=this.uf[c.id]=[]);c.ue?c.ue.value=b:(c.ue={next:this.Ye,Zi:this.Ye.Zi,head:this.Ye,key:a,value:b},c.list.push(c.ue),this.Ye.Zi.next=c.ue,this.Ye.Zi=c.ue,this.size++);return this};c.prototype["delete"]=function(a){a=d(this,a);return a.ue&&a.list?(a.list.splice(a.index,1),a.list.length||delete this.uf[a.id],a.ue.Zi.next=a.ue.next,
a.ue.next.Zi=a.ue.Zi,a.ue.head=null,this.size--,!0):!1};c.prototype.clear=function(){this.uf={};this.Ye=this.Ye.Zi=f();this.size=0};c.prototype.has=function(a){return!!d(this,a).ue};c.prototype.get=function(a){return(a=d(this,a).ue)&&a.value};c.prototype.entries=function(){return e(this,function(a){return[a.key,a.value]})};c.prototype.keys=function(){return e(this,function(a){return a.key})};c.prototype.values=function(){return e(this,function(a){return a.value})};c.prototype.forEach=function(a,b){for(var c=
this.entries(),d;!(d=c.next()).done;)d=d.value,a.call(b,d[1],d[0],this)};c.prototype[window.Symbol.iterator]=c.prototype.entries;var d=function(a,c){var d=c&&typeof c;"object"==d||"function"==d?b.has(c)?d=b.get(c):(d=""+ ++h,b.set(c,d)):d="p_"+c;var e=a.uf[d];if(e&&Ha(a.uf,d))for(a=0;a<e.length;a++){var f=e[a];if(c!==c&&f.key!==f.key||c===f.key)return{id:d,list:e,index:a,ue:f}}return{id:d,list:e,index:-1,ue:void 0}},e=function(a,b){var c=a.Ye;return Ea(function(){if(c){for(;c.head!=a.Ye;)c=c.Zi;for(;c.next!=
c.head;)return c=c.next,{done:!1,value:b(c)};c=null}return{done:!0,value:void 0}})},f=function(){var a={};return a.Zi=a.next=a.head=a},h=0;return c});
Aa("Set",function(a){if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var b=Object.seal({x:4}),d=new a(_.ea([b]));if(!d.has(b)||1!=d.size||d.add(b)!=d||1!=d.size||d.add({x:4})!=d||2!=d.size)return!1;var e=d.entries(),f=e.next();if(f.done||f.value[0]!=b||f.value[1]!=b)return!1;f=e.next();return f.done||f.value[0]==b||4!=f.value[0].x||f.value[1]!=f.value[0]?!1:e.next().done}catch(h){return!1}}())return a;Fa();var b=function(a){this.U=new window.Map;
if(a){a=_.ea(a);for(var b;!(b=a.next()).done;)this.add(b.value)}this.size=this.U.size};b.prototype.add=function(a){a=0===a?0:a;this.U.set(a,a);this.size=this.U.size;return this};b.prototype["delete"]=function(a){a=this.U["delete"](a);this.size=this.U.size;return a};b.prototype.clear=function(){this.U.clear();this.size=0};b.prototype.has=function(a){return this.U.has(a)};b.prototype.entries=function(){return this.U.entries()};b.prototype.values=function(){return this.U.values()};b.prototype.keys=b.prototype.values;
b.prototype[window.Symbol.iterator]=b.prototype.values;b.prototype.forEach=function(a,b){var c=this;this.U.forEach(function(d){return a.call(b,d,d,c)})};return b});Aa("Number.isFinite",function(a){return a?a:function(a){return"number"!==typeof a?!1:!(0,window.isNaN)(a)&&window.Infinity!==a&&-window.Infinity!==a}});Aa("Object.is",function(a){return a?a:function(a,c){return a===c?0!==a||1/a===1/c:a!==a&&c!==c}});_.Ja=_.Ja||{};_.m=this;_.Ka=function(a){return void 0!==a};
_.r=function(a){return"string"==typeof a};
_.La=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};_.Ma=function(a){return"array"==_.La(a)};_.Na="closure_uid_"+(1E9*Math.random()>>>0);_.Oa=Date.now||function(){return+new Date};_.u=function(a,b){a=a.split(".");var c=_.m;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&_.Ka(b)?c[d]=b:c=c[d]&&c[d]!==Object.prototype[d]?c[d]:c[d]={}};
_.x=function(a,b){function c(){}c.prototype=b.prototype;a.H=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.xp=function(a,c,f){for(var d=Array(arguments.length-2),e=2;e<arguments.length;e++)d[e-2]=arguments[e];return b.prototype[c].apply(a,d)}};
_.Ua=window.osapi=window.osapi||{};
window.___jsl=window.___jsl||{};
(window.___jsl.cd=window.___jsl.cd||[]).push({gwidget:{parsetags:"explicit"},appsapi:{plus_one_service:"/plus/v1"},csi:{rate:.01},poshare:{hangoutContactPickerServer:"https://plus.google.com"},gappsutil:{required_scopes:["https://www.googleapis.com/auth/plus.me","https://www.googleapis.com/auth/plus.people.recommended"],display_on_page_ready:!1},appsutil:{required_scopes:["https://www.googleapis.com/auth/plus.me","https://www.googleapis.com/auth/plus.people.recommended"],display_on_page_ready:!1},
"oauth-flow":{authUrl:"https://accounts.google.com/o/oauth2/auth",proxyUrl:"https://accounts.google.com/o/oauth2/postmessageRelay",redirectUri:"postmessage"},iframes:{sharebox:{params:{json:"&"},url:":socialhost:/:session_prefix:_/sharebox/dialog"},plus:{url:":socialhost:/:session_prefix:_/widget/render/badge?usegapi=1"},":socialhost:":"https://apis.google.com",":im_socialhost:":"https://plus.googleapis.com",domains_suggest:{url:"https://domains.google.com/suggest/flow"},card:{params:{s:"#",userid:"&"},
url:":socialhost:/:session_prefix:_/hovercard/internalcard"},":signuphost:":"https://plus.google.com",":gplus_url:":"https://plus.google.com",plusone:{url:":socialhost:/:session_prefix:_/+1/fastbutton?usegapi=1"},plus_share:{url:":socialhost:/:session_prefix:_/+1/sharebutton?plusShare=true&usegapi=1"},plus_circle:{url:":socialhost:/:session_prefix:_/widget/plus/circle?usegapi=1"},plus_followers:{url:":socialhost:/_/im/_/widget/render/plus/followers?usegapi=1"},configurator:{url:":socialhost:/:session_prefix:_/plusbuttonconfigurator?usegapi=1"},
appcirclepicker:{url:":socialhost:/:session_prefix:_/widget/render/appcirclepicker"},page:{url:":socialhost:/:session_prefix:_/widget/render/page?usegapi=1"},person:{url:":socialhost:/:session_prefix:_/widget/render/person?usegapi=1"},community:{url:":ctx_socialhost:/:session_prefix::im_prefix:_/widget/render/community?usegapi=1"},follow:{url:":socialhost:/:session_prefix:_/widget/render/follow?usegapi=1"},commentcount:{url:":socialhost:/:session_prefix:_/widget/render/commentcount?usegapi=1"},comments:{url:":socialhost:/:session_prefix:_/widget/render/comments?usegapi=1"},
youtube:{url:":socialhost:/:session_prefix:_/widget/render/youtube?usegapi=1"},reportabuse:{url:":socialhost:/:session_prefix:_/widget/render/reportabuse?usegapi=1"},additnow:{url:":socialhost:/additnow/additnow.html"},appfinder:{url:"https://gsuite.google.com/:session_prefix:marketplace/appfinder?usegapi=1"},":source:":"1p"},poclient:{update_session:"google.updateSessionCallback"},"googleapis.config":{methods:{"pos.plusones.list":!0,"pos.plusones.get":!0,"pos.plusones.insert":!0,"pos.plusones.delete":!0,
"pos.plusones.getSignupState":!0},versions:{pos:"v1"},rpc:"/rpc",root:"https://content.googleapis.com","root-1p":"https://clients6.google.com",useGapiForXd3:!0,xd3:"/static/proxy.html",developerKey:"AIzaSyCKSbrvQasunBoV16zDH9R33D88CeLr9gQ",auth:{useInterimAuth:!1}},report:{apis:["iframes\\..*","gadgets\\..*","gapi\\.appcirclepicker\\..*","gapi\\.client\\..*"],rate:1E-4},client:{perApiBatch:!0}});

var cb,eb,fb;_.Wa=function(a){return"number"==typeof a};_.Xa=function(){};_.Ya=function(a){var b=_.La(a);return"array"==b||"object"==b&&"number"==typeof a.length};_.ab=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};_.bb=function(a){return"function"==_.La(a)};cb=0;_.db=function(a){return a[_.Na]||(a[_.Na]=++cb)};eb=function(a,b,c){return a.call.apply(a.bind,arguments)};
fb=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};_.A=function(a,b,c){_.A=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?eb:fb;return _.A.apply(null,arguments)};
_.gb=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if(_.r(a))return _.r(b)&&1==b.length?a.indexOf(b,0):-1;for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};_.ib=Array.prototype.lastIndexOf?function(a,b){return Array.prototype.lastIndexOf.call(a,b,a.length-1)}:function(a,b){var c=a.length-1;0>c&&(c=Math.max(0,a.length+c));if(_.r(a))return _.r(b)&&1==b.length?a.lastIndexOf(b,c):-1;for(;0<=c;c--)if(c in a&&a[c]===b)return c;return-1};
_.jb=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.r(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};_.lb=Array.prototype.filter?function(a,b){return Array.prototype.filter.call(a,b,void 0)}:function(a,b){for(var c=a.length,d=[],e=0,f=_.r(a)?a.split(""):a,h=0;h<c;h++)if(h in f){var k=f[h];b.call(void 0,k,h,a)&&(d[e++]=k)}return d};
_.mb=Array.prototype.map?function(a,b){return Array.prototype.map.call(a,b,void 0)}:function(a,b){for(var c=a.length,d=Array(c),e=_.r(a)?a.split(""):a,f=0;f<c;f++)f in e&&(d[f]=b.call(void 0,e[f],f,a));return d};_.ob=Array.prototype.some?function(a,b,c){return Array.prototype.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.r(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1}; _.pb=Array.prototype.every?function(a,b,c){return Array.prototype.every.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.r(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&!b.call(c,e[f],f,a))return!1;return!0};_.qb=function(a,b){return 0<=(0,_.gb)(a,b)};
var ub;_.rb=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};_.sb=String.prototype.repeat?function(a,b){return a.repeat(b)}:function(a,b){return Array(b+1).join(a)};
_.vb=function(a,b){var c=0;a=(0,_.rb)(String(a)).split(".");b=(0,_.rb)(String(b)).split(".");for(var d=Math.max(a.length,b.length),e=0;0==c&&e<d;e++){var f=a[e]||"",h=b[e]||"";do{f=/(\d*)(\D*)(.*)/.exec(f)||["","","",""];h=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];if(0==f[0].length&&0==h[0].length)break;c=ub(0==f[1].length?0:(0,window.parseInt)(f[1],10),0==h[1].length?0:(0,window.parseInt)(h[1],10))||ub(0==f[2].length,0==h[2].length)||ub(f[2],h[2]);f=f[3];h=h[3]}while(0==c)}return c}; ub=function(a,b){return a<b?-1:a>b?1:0};_.wb=2147483648*Math.random()|0;
a:{var yb=_.m.navigator;if(yb){var Ab=yb.userAgent;if(Ab){_.xb=Ab;break a}}_.xb=""}_.Bb=function(a){return-1!=_.xb.indexOf(a)};var Fb;_.Eb=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};Fb="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");_.Gb=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Fb.length;f++)c=Fb[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};
_.Hb=function(){return _.Bb("Opera")};_.Jb=function(){return _.Bb("Trident")||_.Bb("MSIE")};_.Kb=function(){return _.Bb("iPhone")&&!_.Bb("iPod")&&!_.Bb("iPad")};_.Lb=function(){return _.Kb()||_.Bb("iPad")||_.Bb("iPod")};var Mb=function(a){Mb[" "](a);return a},Pb;Mb[" "]=_.Xa;_.Nb=function(a,b){try{return Mb(a[b]),!0}catch(c){}return!1};Pb=function(a,b){var c=Ob;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var dc,ec,Ob,mc;_.Qb=_.Hb();_.B=_.Jb();_.Rb=_.Bb("Edge");_.Sb=_.Rb||_.B;_.Tb=_.Bb("Gecko")&&!(-1!=_.xb.toLowerCase().indexOf("webkit")&&!_.Bb("Edge"))&&!(_.Bb("Trident")||_.Bb("MSIE"))&&!_.Bb("Edge");_.Ub=-1!=_.xb.toLowerCase().indexOf("webkit")&&!_.Bb("Edge");_.Vb=_.Ub&&_.Bb("Mobile");_.Wb=_.Bb("Macintosh");_.Xb=_.Bb("Windows");_.Yb=_.Bb("Linux")||_.Bb("CrOS");_.Zb=_.Bb("Android");_.$b=_.Kb();_.ac=_.Bb("iPad");_.bc=_.Bb("iPod");_.cc=_.Lb();
dc=function(){var a=_.m.document;return a?a.documentMode:void 0};a:{var fc="",gc=function(){var a=_.xb;if(_.Tb)return/rv:([^\);]+)(\)|;)/.exec(a);if(_.Rb)return/Edge\/([\d\.]+)/.exec(a);if(_.B)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(_.Ub)return/WebKit\/(\S+)/.exec(a);if(_.Qb)return/(?:Version)[ \/]?(\S+)/.exec(a)}();gc&&(fc=gc?gc[1]:"");if(_.B){var hc=dc();if(null!=hc&&hc>(0,window.parseFloat)(fc)){ec=String(hc);break a}}ec=fc}_.ic=ec;Ob={}; _.jc=function(a){return Pb(a,function(){return 0<=_.vb(_.ic,a)})};_.lc=function(a){return Number(_.kc)>=a};var nc=_.m.document;mc=nc&&_.B?dc()||("CSS1Compat"==nc.compatMode?(0,window.parseInt)(_.ic,10):5):void 0;_.kc=mc;

var qc,uc,vc,wc,xc,yc,zc,Ac;_.oc=function(a,b){return _.ba[a]=b};_.rc=function(a){return Array.prototype.concat.apply([],arguments)};_.sc=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};_.tc=function(a,b){return 0==a.lastIndexOf(b,0)};uc=/&/g;vc=/</g;wc=/>/g;xc=/"/g;yc=/'/g;zc=/\x00/g;Ac=/[\x00&<>"']/;
_.Bc=function(a){if(!Ac.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(uc,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(vc,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(wc,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(xc,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(yc,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(zc,"&#0;"));return a};_.Cc=function(a){return String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()})};_.Dc=function(a,b){for(var c in a)if(a[c]==b)return!0;return!1};
var Fc,Gc;Fc=!_.B||_.lc(9);Gc=!_.Tb&&!_.B||_.B&&_.lc(9)||_.Tb&&_.jc("1.9.1");_.Hc=_.B&&!_.jc("9");_.Ic=_.B||_.Qb||_.Ub;_.Jc=_.B&&!_.lc(9);_.Mc=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}};var Oc,Nc;_.Pc=function(a,b){this.YD=a===Nc&&b||"";this.nQ=Oc};_.Pc.prototype.Ih=!0;_.Pc.prototype.lg=function(){return this.YD};_.Pc.prototype.toString=function(){return"Const{"+this.YD+"}"};_.Qc=function(a){return a instanceof _.Pc&&a.constructor===_.Pc&&a.nQ===Oc?a.YD:"type_error:Const"};_.Rc=function(a){return new _.Pc(Nc,a)};Oc={};Nc={};
var Sc;_.Tc=function(){this.zC="";this.wQ=Sc};_.Tc.prototype.Ih=!0;_.Tc.prototype.lg=function(){return this.zC};_.Tc.prototype.fB=!0;_.Tc.prototype.yl=function(){return 1};_.Uc=function(a){if(a instanceof _.Tc&&a.constructor===_.Tc&&a.wQ===Sc)return a.zC;_.La(a);return"type_error:TrustedResourceUrl"};_.Xc=function(a){return _.Wc(_.Qc(a))};Sc={};_.Wc=function(a){var b=new _.Tc;b.zC=a;return b};
var ad,Yc,bd;_.Zc=function(){this.lm="";this.XP=Yc};_.Zc.prototype.Ih=!0;_.Zc.prototype.lg=function(){return this.lm};_.Zc.prototype.fB=!0;_.Zc.prototype.yl=function(){return 1};_.$c=function(a){if(a instanceof _.Zc&&a.constructor===_.Zc&&a.XP===Yc)return a.lm;_.La(a);return"type_error:SafeUrl"};ad=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i;_.cd=function(a){if(a instanceof _.Zc)return a;a="object"==typeof a&&a.Ih?a.lg():String(a);ad.test(a)||(a="about:invalid#zClosurez");return bd(a)}; _.dd=function(a){if(a instanceof _.Zc)return a;a="object"==typeof a&&a.Ih?a.lg():String(a);ad.test(a)||(a="about:invalid#zClosurez");return bd(a)};Yc={};bd=function(a){var b=new _.Zc;b.lm=a;return b};bd("about:blank");
_.hd=function(){this.yC="";this.WP=_.ed};_.hd.prototype.Ih=!0;_.ed={};_.hd.prototype.lg=function(){return this.yC};_.hd.prototype.Li=function(a){this.yC=a;return this};_.id=(new _.hd).Li("");_.kd=function(){this.xC="";this.VP=_.jd};_.kd.prototype.Ih=!0;_.jd={};_.md=function(a){a=_.Qc(a);return 0===a.length?ld:(new _.kd).Li(a)};_.kd.prototype.lg=function(){return this.xC};_.kd.prototype.Li=function(a){this.xC=a;return this};var ld=(new _.kd).Li("");
var nd;_.od=function(){this.lm="";this.UP=nd;this.iH=null};_.od.prototype.fB=!0;_.od.prototype.yl=function(){return this.iH};_.od.prototype.Ih=!0;_.od.prototype.lg=function(){return this.lm};_.pd=function(a){if(a instanceof _.od&&a.constructor===_.od&&a.UP===nd)return a.lm;_.La(a);return"type_error:SafeHtml"};nd={};_.qd=function(a,b){return(new _.od).Li(a,b)};_.od.prototype.Li=function(a,b){this.lm=a;this.iH=b;return this};_.qd("<!DOCTYPE html>",0);_.td=_.qd("",0);_.ud=_.qd("<br>",0);
_.vd=_.Mc(function(){var a=window.document.createElement("div");a.innerHTML="<div><div></div></div>";var b=a.firstChild.firstChild;a.innerHTML="";return!b.parentElement});_.wd=function(a,b){b=b instanceof _.Zc?b:_.dd(b);a.href=_.$c(b)};var Cd,Fd,Hd;_.zd=function(a){return a?new _.xd(_.yd(a)):qc||(qc=new _.xd)};_.Ad=function(a,b){return _.r(b)?a.getElementById(b):b};
_.Bd=function(a,b,c,d){a=d||a;b=b&&"*"!=b?String(b).toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(b||c))return a.querySelectorAll(b+(c?"."+c:""));if(c&&a.getElementsByClassName){a=a.getElementsByClassName(c);if(b){d={};for(var e=0,f=0,h;h=a[f];f++)b==h.nodeName&&(d[e++]=h);d.length=e;return d}return a}a=a.getElementsByTagName(b||"*");if(c){d={};for(f=e=0;h=a[f];f++)b=h.className,"function"==typeof b.split&&_.qb(b.split(/\s+/),c)&&(d[e++]=h);d.length=e;return d}return a};
_.Dd=function(a,b){_.Eb(b,function(b,d){b&&"object"==typeof b&&b.Ih&&(b=b.lg());"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:Cd.hasOwnProperty(d)?a.setAttribute(Cd[d],b):_.tc(d,"aria-")||_.tc(d,"data-")?a.setAttribute(d,b):a[d]=b})};Cd={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
_.Ed=function(a){return a?a.parentWindow||a.defaultView:window};_.Gd=function(a,b){var c=String(b[0]),d=b[1];if(!Fc&&d&&(d.name||d.type)){c=["<",c];d.name&&c.push(' name="',_.Bc(d.name),'"');if(d.type){c.push(' type="',_.Bc(d.type),'"');var e={};_.Gb(e,d);delete e.type;d=e}c.push(">");c=c.join("")}c=a.createElement(c);d&&(_.r(d)?c.className=d:_.Ma(d)?c.className=d.join(" "):_.Dd(c,d));2<b.length&&Fd(a,c,b,2);return c};
Fd=function(a,b,c,d){function e(c){c&&b.appendChild(_.r(c)?a.createTextNode(c):c)}for(;d<c.length;d++){var f=c[d];!_.Ya(f)||_.ab(f)&&0<f.nodeType?e(f):(0,_.jb)(Hd(f)?_.sc(f):f,e)}};_.Id=function(a){return window.document.createElement(String(a))};_.Kd=function(a){if(1!=a.nodeType)return!1;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "SOURCE":case "STYLE":case "TRACK":case "WBR":return!1}return!0};
_.Ld=function(a,b){Fd(_.yd(a),a,arguments,1)};_.Md=function(a){for(var b;b=a.firstChild;)a.removeChild(b)};_.Nd=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b)};_.Od=function(a){return a&&a.parentNode?a.parentNode.removeChild(a):null};_.Pd=function(a){var b,c=a.parentNode;if(c&&11!=c.nodeType){if(a.removeNode)return a.removeNode(!1);for(;b=a.firstChild;)c.insertBefore(b,a);return _.Od(a)}};
_.Qd=function(a){return Gc&&void 0!=a.children?a.children:(0,_.lb)(a.childNodes,function(a){return 1==a.nodeType})};_.Rd=function(a){return _.ab(a)&&1==a.nodeType};_.Sd=function(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};_.yd=function(a){return 9==a.nodeType?a:a.ownerDocument||a.document};
_.Td=function(a,b){if("textContent"in a)a.textContent=b;else if(3==a.nodeType)a.data=String(b);else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=String(b)}else _.Md(a),a.appendChild(_.yd(a).createTextNode(String(b)))};Hd=function(a){if(a&&"number"==typeof a.length){if(_.ab(a))return"function"==typeof a.item||"string"==typeof a.item;if(_.bb(a))return"function"==typeof a.item}return!1};
_.xd=function(a){this.Va=a||_.m.document||window.document};_.g=_.xd.prototype;_.g.Da=_.zd;_.g.sD=_.ca(0);_.g.tb=function(){return this.Va};_.g.S=function(a){return _.Ad(this.Va,a)};_.g.getElementsByTagName=function(a,b){return(b||this.Va).getElementsByTagName(String(a))};_.g.ma=function(a,b,c){return _.Gd(this.Va,arguments)};_.g.createElement=function(a){return this.Va.createElement(String(a))};_.g.createTextNode=function(a){return this.Va.createTextNode(String(a))};
_.g.wb=function(){var a=this.Va;return a.parentWindow||a.defaultView};_.g.appendChild=function(a,b){a.appendChild(b)};_.g.append=_.Ld;_.g.canHaveChildren=_.Kd;_.g.Fe=_.Md;_.g.AJ=_.Nd;_.g.removeNode=_.Od;_.g.IS=_.Pd;_.g.Yz=_.Qd;_.g.isElement=_.Rd;_.g.contains=_.Sd;_.g.Lh=_.ca(1);
/*
 gapi.loader.OBJECT_CREATE_TEST_OVERRIDE &&*/
_.Ud=window;_.Vd=window.document;_.Wd=_.Ud.location;_.Yd=/\[native code\]/;_.Zd=function(a,b,c){return a[b]=a[b]||c};_.$d=function(){var a;if((a=Object.create)&&_.Yd.test(a))a=a(null);else{a={};for(var b in a)a[b]=void 0}return a};_.ae=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};_.be=function(a,b){a=a||{};for(var c in a)_.ae(a,c)&&(b[c]=a[c])};_.ce=_.Zd(_.Ud,"gapi",{});
_.de=function(a,b,c){var d=new RegExp("([#].*&|[#])"+b+"=([^&#]*)","g");b=new RegExp("([?#].*&|[?#])"+b+"=([^&#]*)","g");if(a=a&&(d.exec(a)||b.exec(a)))try{c=(0,window.decodeURIComponent)(a[2])}catch(e){}return c};_.ee=new RegExp(/^/.source+/([a-zA-Z][-+.a-zA-Z0-9]*:)?/.source+/(\/\/[^\/?#]*)?/.source+/([^?#]*)?/.source+/(\?([^#]*))?/.source+/(#((#|[^#])*))?/.source+/$/.source);
_.fe=new RegExp(/(%([^0-9a-fA-F%]|[0-9a-fA-F]([^0-9a-fA-F%])?)?)*/.source+/%($|[^0-9a-fA-F]|[0-9a-fA-F]($|[^0-9a-fA-F]))/.source,"g");_.he=new RegExp(/\/?\??#?/.source+"("+/[\/?#]/i.source+"|"+/[\uD800-\uDBFF]/i.source+"|"+/%[c-f][0-9a-f](%[89ab][0-9a-f]){0,2}(%[89ab]?)?/i.source+"|"+/%[0-9a-f]?/i.source+")$","i");
_.je=function(a,b,c){_.ie(a,b,c,"add","at")};_.ie=function(a,b,c,d,e){if(a[d+"EventListener"])a[d+"EventListener"](b,c,!1);else if(a[e+"tachEvent"])a[e+"tachEvent"]("on"+b,c)};_.ke=_.Zd(_.Ud,"___jsl",_.$d());_.Zd(_.ke,"I",0);_.Zd(_.ke,"hel",10);var le,me,ne,oe,pe,qe,re;le=function(a){var b=window.___jsl=window.___jsl||{};b[a]=b[a]||[];return b[a]};me=function(a){var b=window.___jsl=window.___jsl||{};b.cfg=!a&&b.cfg||{};return b.cfg};ne=function(a){return"object"===typeof a&&/\[native code\]/.test(a.push)};
oe=function(a,b,c){if(b&&"object"===typeof b)for(var d in b)!Object.prototype.hasOwnProperty.call(b,d)||c&&"___goc"===d&&"undefined"===typeof b[d]||(a[d]&&b[d]&&"object"===typeof a[d]&&"object"===typeof b[d]&&!ne(a[d])&&!ne(b[d])?oe(a[d],b[d]):b[d]&&"object"===typeof b[d]?(a[d]=ne(b[d])?[]:{},oe(a[d],b[d])):a[d]=b[d])};
pe=function(a){if(a&&!/^\s+$/.test(a)){for(;0==a.charCodeAt(a.length-1);)a=a.substring(0,a.length-1);try{var b=window.JSON.parse(a)}catch(c){}if("object"===typeof b)return b;try{b=(new Function("return ("+a+"\n)"))()}catch(c){}if("object"===typeof b)return b;try{b=(new Function("return ({"+a+"\n})"))()}catch(c){}return"object"===typeof b?b:{}}};
qe=function(a,b){var c={___goc:void 0};a.length&&a[a.length-1]&&Object.hasOwnProperty.call(a[a.length-1],"___goc")&&"undefined"===typeof a[a.length-1].___goc&&(c=a.pop());oe(c,b);a.push(c)};
re=function(a){me(!0);var b=window.___gcfg,c=le("cu"),d=window.___gu;b&&b!==d&&(qe(c,b),window.___gu=b);b=le("cu");var e=window.document.scripts||window.document.getElementsByTagName("script")||[];d=[];var f=[];f.push.apply(f,le("us"));for(var h=0;h<e.length;++h)for(var k=e[h],l=0;l<f.length;++l)k.src&&0==k.src.indexOf(f[l])&&d.push(k);0==d.length&&0<e.length&&e[e.length-1].src&&d.push(e[e.length-1]);for(e=0;e<d.length;++e)d[e].getAttribute("gapi_processed")||(d[e].setAttribute("gapi_processed",!0),
(f=d[e])?(h=f.nodeType,f=3==h||4==h?f.nodeValue:f.textContent||f.innerText||f.innerHTML||""):f=void 0,(f=pe(f))&&b.push(f));a&&qe(c,a);d=le("cd");a=0;for(b=d.length;a<b;++a)oe(me(),d[a],!0);d=le("ci");a=0;for(b=d.length;a<b;++a)oe(me(),d[a],!0);a=0;for(b=c.length;a<b;++a)oe(me(),c[a],!0)};_.C=function(a,b){var c=me();if(!a)return c;a=a.split("/");for(var d=0,e=a.length;c&&"object"===typeof c&&d<e;++d)c=c[a[d]];return d===a.length&&void 0!==c?c:b}; _.se=function(a,b){var c;if("string"===typeof a){var d=c={};a=a.split("/");for(var e=0,f=a.length;e<f-1;++e){var h={};d=d[a[e]]=h}d[a[e]]=b}else c=a;re(c)};
var te=function(){var a=window.__GOOGLEAPIS;a&&(a.googleapis&&!a["googleapis.config"]&&(a["googleapis.config"]=a.googleapis),_.Zd(_.ke,"ci",[]).push(a),window.__GOOGLEAPIS=void 0)};te&&te();re();_.u("gapi.config.get",_.C);_.u("gapi.config.update",_.se);
_.ue=function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(_.Ya(d)){var e=a.length||0,f=d.length||0;a.length=e+f;for(var h=0;h<f;h++)a[e+h]=d[h]}else a.push(d)}};_.ve=function(a){return/^[\s\xa0]*$/.test(a)};_.we=function(a,b){var c=b||window.document;if(c.getElementsByClassName)a=c.getElementsByClassName(a)[0];else{c=window.document;var d=b||c;a=d.querySelectorAll&&d.querySelector&&a?d.querySelector(a?"."+a:""):_.Bd(c,"*",a,b)[0]||null}return a||null};

var De,Ee,Fe,Ge,He,Ie,Je,Ke,Le,Me,Ne,Oe,Pe,Qe,Re,Se,Te,Ue,Ve,We,Xe,Ye,Ze,$e,af,bf,cf,df,ef,ff,gf,kf,lf;Fe=void 0;Ge=function(a){try{return _.m.JSON.parse.call(_.m.JSON,a)}catch(b){return!1}};He=function(a){return Object.prototype.toString.call(a)};Ie=He(0);Je=He(new Date(0));Ke=He(!0);Le=He("");Me=He({});Ne=He([]);
Oe=function(a,b){if(b)for(var c=0,d=b.length;c<d;++c)if(a===b[c])throw new TypeError("Converting circular structure to JSON");d=typeof a;if("undefined"!==d){c=Array.prototype.slice.call(b||[],0);c[c.length]=a;b=[];var e=He(a);if(null!=a&&"function"===typeof a.toJSON&&(Object.prototype.hasOwnProperty.call(a,"toJSON")||(e!==Ne||a.constructor!==Array&&a.constructor!==Object)&&(e!==Me||a.constructor!==Array&&a.constructor!==Object)&&e!==Le&&e!==Ie&&e!==Ke&&e!==Je))return Oe(a.toJSON.call(a),c);if(null==
a)b[b.length]="null";else if(e===Ie)a=Number(a),(0,window.isNaN)(a)||(0,window.isNaN)(a-a)?a="null":-0===a&&0>1/a&&(a="-0"),b[b.length]=String(a);else if(e===Ke)b[b.length]=String(!!Number(a));else{if(e===Je)return Oe(a.toISOString.call(a),c);if(e===Ne&&He(a.length)===Ie){b[b.length]="[";var f=0;for(d=Number(a.length)>>0;f<d;++f)f&&(b[b.length]=","),b[b.length]=Oe(a[f],c)||"null";b[b.length]="]"}else if(e==Le&&He(a.length)===Ie){b[b.length]='"';f=0;for(c=Number(a.length)>>0;f<c;++f)d=String.prototype.charAt.call(a,
f),e=String.prototype.charCodeAt.call(a,f),b[b.length]="\b"===d?"\\b":"\f"===d?"\\f":"\n"===d?"\\n":"\r"===d?"\\r":"\t"===d?"\\t":"\\"===d||'"'===d?"\\"+d:31>=e?"\\u"+(e+65536).toString(16).substr(1):32<=e&&65535>=e?d:"\ufffd";b[b.length]='"'}else if("object"===d){b[b.length]="{";d=0;for(f in a)Object.prototype.hasOwnProperty.call(a,f)&&(e=Oe(a[f],c),void 0!==e&&(d++&&(b[b.length]=","),b[b.length]=Oe(f),b[b.length]=":",b[b.length]=e));b[b.length]="}"}else return}return b.join("")}};Pe=/[\0-\x07\x0b\x0e-\x1f]/;
Qe=/^([^"]*"([^\\"]|\\.)*")*[^"]*"([^"\\]|\\.)*[\0-\x1f]/;Re=/^([^"]*"([^\\"]|\\.)*")*[^"]*"([^"\\]|\\.)*\\[^\\\/"bfnrtu]/;Se=/^([^"]*"([^\\"]|\\.)*")*[^"]*"([^"\\]|\\.)*\\u([0-9a-fA-F]{0,3}[^0-9a-fA-F])/;Te=/"([^\0-\x1f\\"]|\\[\\\/"bfnrt]|\\u[0-9a-fA-F]{4})*"/g;Ue=/-?(0|[1-9][0-9]*)(\.[0-9]+)?([eE][-+]?[0-9]+)?/g;Ve=/[ \t\n\r]+/g;We=/[^"]:/;Xe=/""/g;Ye=/true|false|null/g;Ze=/00/;$e=/[\{]([^0\}]|0[^:])/;af=/(^|\[)[,:]|[,:](\]|\}|[,:]|$)/;bf=/[^\[,:][\[\{]/;cf=/^(\{|\}|\[|\]|,|:|0)+/;df=/\u2028/g;
ef=/\u2029/g;
ff=function(a){a=String(a);if(Pe.test(a)||Qe.test(a)||Re.test(a)||Se.test(a))return!1;var b=a.replace(Te,'""');b=b.replace(Ue,"0");b=b.replace(Ve,"");if(We.test(b))return!1;b=b.replace(Xe,"0");b=b.replace(Ye,"0");if(Ze.test(b)||$e.test(b)||af.test(b)||bf.test(b)||!b||(b=b.replace(cf,"")))return!1;a=a.replace(df,"\\u2028").replace(ef,"\\u2029");b=void 0;try{b=Fe?[Ge(a)]:eval("(function (var_args) {\n  return Array.prototype.slice.call(arguments, 0);\n})(\n"+a+"\n)")}catch(c){return!1}return b&&1===
b.length?b[0]:!1};gf=function(){var a=((_.m.document||{}).scripts||[]).length;if((void 0===De||void 0===Fe||Ee!==a)&&-1!==Ee){De=Fe=!1;Ee=-1;try{try{Fe=!!_.m.JSON&&'{"a":[3,true,"1970-01-01T00:00:00.000Z"]}'===_.m.JSON.stringify.call(_.m.JSON,{a:[3,!0,new Date(0)],c:function(){}})&&!0===Ge("true")&&3===Ge('[{"a":3}]')[0].a}catch(b){}De=Fe&&!Ge("[00]")&&!Ge('"\u0007"')&&!Ge('"\\0"')&&!Ge('"\\v"')}finally{Ee=a}}};_.hf=function(a){if(-1===Ee)return!1;gf();return(De?Ge:ff)(a)};
_.jf=function(a){if(-1!==Ee)return gf(),Fe?_.m.JSON.stringify.call(_.m.JSON,a):Oe(a)};kf=!Date.prototype.toISOString||"function"!==typeof Date.prototype.toISOString||"1970-01-01T00:00:00.000Z"!==(new Date(0)).toISOString();
lf=function(){var a=Date.prototype.getUTCFullYear.call(this);return[0>a?"-"+String(1E6-a).substr(1):9999>=a?String(1E4+a).substr(1):"+"+String(1E6+a).substr(1),"-",String(101+Date.prototype.getUTCMonth.call(this)).substr(1),"-",String(100+Date.prototype.getUTCDate.call(this)).substr(1),"T",String(100+Date.prototype.getUTCHours.call(this)).substr(1),":",String(100+Date.prototype.getUTCMinutes.call(this)).substr(1),":",String(100+Date.prototype.getUTCSeconds.call(this)).substr(1),".",String(1E3+Date.prototype.getUTCMilliseconds.call(this)).substr(1), "Z"].join("")};Date.prototype.toISOString=kf?lf:Date.prototype.toISOString;

var ih;ih=/^https?:\/\/(?:\w|[\-\.])+\.google\.(?:\w|[\-:\.])+(?:\/[^\?#]*)?\/u\/(\d)\//;
_.jh=function(a){var b=_.C("googleapis.config/sessionIndex");"string"===typeof b&&254<b.length&&(b=null);null==b&&(b=window.__X_GOOG_AUTHUSER);"string"===typeof b&&254<b.length&&(b=null);if(null==b){var c=window.google;c&&(b=c.authuser)}"string"===typeof b&&254<b.length&&(b=null);null==b&&(a=a||window.location.href,b=_.de(a,"authuser")||null,null==b&&(b=(b=a.match(ih))?b[1]:null));if(null==b)return null;b=String(b);254<b.length&&(b=null);return b};

var mh=function(){this.Jj=-1};_.nh=function(){this.Jj=64;this.Gc=[];this.ty=[];this.DQ=[];this.$v=[];this.$v[0]=128;for(var a=1;a<this.Jj;++a)this.$v[a]=0;this.cx=this.In=0;this.reset()};_.x(_.nh,mh);_.nh.prototype.reset=function(){this.Gc[0]=1732584193;this.Gc[1]=4023233417;this.Gc[2]=2562383102;this.Gc[3]=271733878;this.Gc[4]=3285377520;this.cx=this.In=0};
var oh=function(a,b,c){c||(c=0);var d=a.DQ;if(_.r(b))for(var e=0;16>e;e++)d[e]=b.charCodeAt(c)<<24|b.charCodeAt(c+1)<<16|b.charCodeAt(c+2)<<8|b.charCodeAt(c+3),c+=4;else for(e=0;16>e;e++)d[e]=b[c]<<24|b[c+1]<<16|b[c+2]<<8|b[c+3],c+=4;for(e=16;80>e;e++){var f=d[e-3]^d[e-8]^d[e-14]^d[e-16];d[e]=(f<<1|f>>>31)&4294967295}b=a.Gc[0];c=a.Gc[1];var h=a.Gc[2],k=a.Gc[3],l=a.Gc[4];for(e=0;80>e;e++){if(40>e)if(20>e){f=k^c&(h^k);var n=1518500249}else f=c^h^k,n=1859775393;else 60>e?(f=c&h|k&(c|h),n=2400959708):
(f=c^h^k,n=3395469782);f=(b<<5|b>>>27)+f+l+n+d[e]&4294967295;l=k;k=h;h=(c<<30|c>>>2)&4294967295;c=b;b=f}a.Gc[0]=a.Gc[0]+b&4294967295;a.Gc[1]=a.Gc[1]+c&4294967295;a.Gc[2]=a.Gc[2]+h&4294967295;a.Gc[3]=a.Gc[3]+k&4294967295;a.Gc[4]=a.Gc[4]+l&4294967295};
_.nh.prototype.update=function(a,b){if(null!=a){_.Ka(b)||(b=a.length);for(var c=b-this.Jj,d=0,e=this.ty,f=this.In;d<b;){if(0==f)for(;d<=c;)oh(this,a,d),d+=this.Jj;if(_.r(a))for(;d<b;){if(e[f]=a.charCodeAt(d),++f,++d,f==this.Jj){oh(this,e);f=0;break}}else for(;d<b;)if(e[f]=a[d],++f,++d,f==this.Jj){oh(this,e);f=0;break}}this.In=f;this.cx+=b}};
_.nh.prototype.digest=function(){var a=[],b=8*this.cx;56>this.In?this.update(this.$v,56-this.In):this.update(this.$v,this.Jj-(this.In-56));for(var c=this.Jj-1;56<=c;c--)this.ty[c]=b&255,b/=256;oh(this,this.ty);for(c=b=0;5>c;c++)for(var d=24;0<=d;d-=8)a[b]=this.Gc[c]>>d&255,++b;return a};

_.ph=function(){this.MD=new _.nh};_.g=_.ph.prototype;_.g.reset=function(){this.MD.reset()};_.g.oN=function(a){this.MD.update(a)};_.g.hH=function(){return this.MD.digest()};_.g.oE=function(a){a=(0,window.unescape)((0,window.encodeURIComponent)(a));for(var b=[],c=0,d=a.length;c<d;++c)b.push(a.charCodeAt(c));this.oN(b)};_.g.Pg=function(){for(var a=this.hH(),b="",c=0;c<a.length;c++)b+="0123456789ABCDEF".charAt(Math.floor(a[c]/16))+"0123456789ABCDEF".charAt(a[c]%16);return b};

var Qj,Pj,Wj,Xj,Rj,Uj,Sj,Yj,Tj;_.Vj=function(){if(Pj){var a=new _.Ud.Uint32Array(1);Qj.getRandomValues(a);a=Number("0."+a[0])}else a=Rj,a+=(0,window.parseInt)(Sj.substr(0,20),16),Sj=Tj(Sj),a/=Uj+Math.pow(16,20);return a};Qj=_.Ud.crypto;Pj=!1;Wj=0;Xj=0;Rj=1;Uj=0;Sj="";Yj=function(a){a=a||_.Ud.event;var b=a.screenX+a.clientX<<16;b+=a.screenY+a.clientY;b*=(new Date).getTime()%1E6;Rj=Rj*b%Uj;0<Wj&&++Xj==Wj&&_.ie(_.Ud,"mousemove",Yj,"remove","de")};Tj=function(a){var b=new _.ph;b.oE(a);return b.Pg()};
Pj=!!Qj&&"function"==typeof Qj.getRandomValues;Pj||(Uj=1E6*(window.screen.width*window.screen.width+window.screen.height),Sj=Tj(_.Vd.cookie+"|"+_.Vd.location+"|"+(new Date).getTime()+"|"+Math.random()),Wj=_.C("random/maxObserveMousemove")||0,0!=Wj&&_.je(_.Ud,"mousemove",Yj));

var ak,ek,fk,gk,hk,ik,jk,kk,lk,mk,nk,ok,pk,tk,vk,wk,xk,yk,zk,Ak;_.Zj=function(a,b){b=b instanceof _.Zc?b:_.dd(b);a.href=_.$c(b)};_.bk=function(a){return!!a&&"object"===typeof a&&_.Yd.test(a.push)};_.ck=function(a){for(var b=0;b<this.length;b++)if(this[b]===a)return b;return-1};_.dk=function(a,b){if(!a)throw Error(b||"");};ek=/&/g;fk=/</g;gk=/>/g;hk=/"/g;ik=/'/g;jk=function(a){return String(a).replace(ek,"&amp;").replace(fk,"&lt;").replace(gk,"&gt;").replace(hk,"&quot;").replace(ik,"&#39;")};kk=/[\ud800-\udbff][\udc00-\udfff]|[^!-~]/g;
lk=/%([a-f]|[0-9a-fA-F][a-f])/g;mk=/^(https?|ftp|file|chrome-extension):$/i;
nk=function(a){a=String(a);a=a.replace(kk,function(a){try{return(0,window.encodeURIComponent)(a)}catch(f){return(0,window.encodeURIComponent)(a.replace(/^[^%]+$/g,"\ufffd"))}}).replace(_.fe,function(a){return a.replace(/%/g,"%25")}).replace(lk,function(a){return a.toUpperCase()});a=a.match(_.ee)||[];var b=_.$d(),c=function(a){return a.replace(/\\/g,"%5C").replace(/\^/g,"%5E").replace(/`/g,"%60").replace(/\{/g,"%7B").replace(/\|/g,"%7C").replace(/\}/g,"%7D")},d=!!(a[1]||"").match(mk);b.xp=c((a[1]||
"")+(a[2]||"")+(a[3]||(a[2]&&d?"/":"")));d=function(a){return c(a.replace(/\?/g,"%3F").replace(/#/g,"%23"))};b.query=a[5]?[d(a[5])]:[];b.xh=a[7]?[d(a[7])]:[];return b};ok=function(a){return a.xp+(0<a.query.length?"?"+a.query.join("&"):"")+(0<a.xh.length?"#"+a.xh.join("&"):"")};pk=function(a,b){var c=[];if(a)for(var d in a)if(_.ae(a,d)&&null!=a[d]){var e=b?b(a[d]):a[d];c.push((0,window.encodeURIComponent)(d)+"="+(0,window.encodeURIComponent)(e))}return c};
_.qk=function(a,b,c,d){a=nk(a);a.query.push.apply(a.query,pk(b,d));a.xh.push.apply(a.xh,pk(c,d));return ok(a)};
_.rk=function(a,b){var c=nk(b);b=c.xp;c.query.length&&(b+="?"+c.query.join(""));c.xh.length&&(b+="#"+c.xh.join(""));var d="";2E3<b.length&&(c=b,b=b.substr(0,2E3),b=b.replace(_.he,""),d=c.substr(b.length));var e=a.createElement("div");a=a.createElement("a");c=nk(b);b=c.xp;c.query.length&&(b+="?"+c.query.join(""));c.xh.length&&(b+="#"+c.xh.join(""));a.href=b;e.appendChild(a);e.innerHTML=e.innerHTML;b=String(e.firstChild.href);e.parentNode&&e.parentNode.removeChild(e);c=nk(b+d);b=c.xp;c.query.length&&
(b+="?"+c.query.join(""));c.xh.length&&(b+="#"+c.xh.join(""));return b};_.sk=/^https?:\/\/[^\/%\\?#\s]+\/[^\s]*$/i;tk=function(a){for(;a.firstChild;)a.removeChild(a.firstChild)};_.uk=function(a,b){var c=_.Zd(_.ke,"watt",_.$d());_.Zd(c,a,b)};vk=/^https?:\/\/(?:\w|[\-\.])+\.google\.(?:\w|[\-:\.])+(?:\/[^\?#]*)?\/b\/(\d{10,21})\//;
wk=function(a){var b=_.C("googleapis.config/sessionDelegate");"string"===typeof b&&21<b.length&&(b=null);null==b&&(b=(a=(a||window.location.href).match(vk))?a[1]:null);if(null==b)return null;b=String(b);21<b.length&&(b=null);return b};xk=function(){var a=_.ke.onl;if(!a){a=_.$d();_.ke.onl=a;var b=_.$d();a.e=function(a){var c=b[a];c&&(delete b[a],c())};a.a=function(a,d){b[a]=d};a.r=function(a){delete b[a]}}return a};yk=function(a,b){b=b.onload;return"function"===typeof b?(xk().a(a,b),b):null}; zk=function(a){_.dk(/^\w+$/.test(a),"Unsupported id - "+a);xk();return'onload="window.___jsl.onl.e(&#34;'+a+'&#34;)"'};Ak=function(a){xk().r(a)};
var Ck,Dk,Ik;_.Bk={allowtransparency:"true",frameborder:"0",hspace:"0",marginheight:"0",marginwidth:"0",scrolling:"no",style:"",tabindex:"0",vspace:"0",width:"100%"};Ck={allowtransparency:!0,onload:!0};Dk=0;_.Fk=function(a,b){var c=0;do var d=b.id||["I",Dk++,"_",(new Date).getTime()].join("");while(a.getElementById(d)&&5>++c);_.dk(5>c,"Error creating iframe id");return d};_.Gk=function(a,b){return a?b+"/"+a:""};
_.Hk=function(a,b,c,d){var e={},f={};a.documentMode&&9>a.documentMode&&(e.hostiemode=a.documentMode);_.be(d.queryParams||{},e);_.be(d.fragmentParams||{},f);var h=d.pfname;var k=_.$d();_.C("iframes/dropLegacyIdParam")||(k.id=c);k._gfid=c;k.parent=a.location.protocol+"//"+a.location.host;c=_.de(a.location.href,"parent");h=h||"";!h&&c&&(h=_.de(a.location.href,"_gfid","")||_.de(a.location.href,"id",""),h=_.Gk(h,_.de(a.location.href,"pfname","")));h||(c=_.hf(_.de(a.location.href,"jcp","")))&&"object"==
typeof c&&(h=_.Gk(c.id,c.pfname));k.pfname=h;d.connectWithJsonParam&&(h={},h.jcp=_.jf(k),k=h);h=_.de(b,"rpctoken")||e.rpctoken||f.rpctoken;h||(h=d.rpctoken||String(Math.round(1E8*_.Vj())),k.rpctoken=h);d.rpctoken=h;_.be(k,d.connectWithQueryParams?e:f);k=a.location.href;a=_.$d();(h=_.de(k,"_bsh",_.ke.bsh))&&(a._bsh=h);(k=_.ke.dpo?_.ke.h:_.de(k,"jsh",_.ke.h))&&(a.jsh=k);d.hintInFragment?_.be(a,f):_.be(a,e);return _.qk(b,e,f,d.paramsSerializer)};
Ik=function(a){_.dk(!a||_.sk.test(a),"Illegal url for new iframe - "+a)};
_.Jk=function(a,b,c,d,e){Ik(c.src);var f,h=yk(d,c),k=h?zk(d):"";try{window.document.all&&(f=a.createElement('<iframe frameborder="'+jk(String(c.frameborder))+'" scrolling="'+jk(String(c.scrolling))+'" '+k+' name="'+jk(String(c.name))+'"/>'))}catch(n){}finally{f||(f=a.createElement("iframe"),h&&(f.onload=function(){f.onload=null;h.call(this)},Ak(d)))}f.setAttribute("ng-non-bindable","");for(var l in c)a=c[l],"style"===l&&"object"===typeof a?_.be(a,f.style):Ck[l]||f.setAttribute(l,String(a));(l=e&& e.beforeNode||null)||e&&e.dontclear||tk(b);b.insertBefore(f,l);f=l?l.previousSibling:b.lastChild;c.allowtransparency&&(f.allowTransparency=!0);return f};
var Kk,Nk;Kk=/^:[\w]+$/;_.Lk=/:([a-zA-Z_]+):/g;_.Mk=function(){var a=_.jh()||"0",b=wk();var c=_.jh(void 0)||a;var d=wk(void 0),e="";c&&(e+="u/"+(0,window.encodeURIComponent)(String(c))+"/");d&&(e+="b/"+(0,window.encodeURIComponent)(String(d))+"/");c=e||null;(e=(d=!1===_.C("isLoggedIn"))?"_/im/":"")&&(c="");var f=_.C("iframes/:socialhost:"),h=_.C("iframes/:im_socialhost:");return ak={socialhost:f,ctx_socialhost:d?h:f,session_index:a,session_delegate:b,session_prefix:c,im_prefix:e}};
Nk=function(a,b){return _.Mk()[b]||""};_.Ok=function(a){return _.rk(_.Vd,a.replace(_.Lk,Nk))};_.Pk=function(a){var b=a;Kk.test(a)&&(b=_.C("iframes/"+b.substring(1)+"/url"),_.dk(!!b,"Unknown iframe url config for - "+a));return _.Ok(b)};
_.Qk=function(a,b,c){var d=c||{};c=d.attributes||{};_.dk(!(d.allowPost||d.forcePost)||!c.onload,"onload is not supported by post iframe (allowPost or forcePost)");a=_.Pk(a);c=b.ownerDocument||_.Vd;var e=_.Fk(c,d);a=_.Hk(c,a,e,d);var f=_.$d();_.be(_.Bk,f);_.be(d.attributes,f);f.name=f.id=e;f.src=a;d.eurl=a;var h=d||{},k=!!h.allowPost;if(h.forcePost||k&&2E3<a.length){h=nk(a);f.src="";d.dropDataPostorigin||(f["data-postorigin"]=a);a=_.Jk(c,b,f,e);if(-1!=window.navigator.userAgent.indexOf("WebKit")){var l=
a.contentWindow.document;l.open();f=l.createElement("div");k={};var n=e+"_inner";k.name=n;k.src="";k.style="display:none";_.Jk(c,f,k,n,d)}f=(d=h.query[0])?d.split("&"):[];d=[];for(k=0;k<f.length;k++)n=f[k].split("=",2),d.push([(0,window.decodeURIComponent)(n[0]),(0,window.decodeURIComponent)(n[1])]);h.query=[];f=ok(h);_.dk(_.sk.test(f),"Invalid URL: "+f);h=c.createElement("form");h.action=f;h.method="POST";h.target=e;h.style.display="none";for(e=0;e<d.length;e++)f=c.createElement("input"),f.type= "hidden",f.name=d[e][0],f.value=d[e][1],h.appendChild(f);b.appendChild(h);h.submit();h.parentNode.removeChild(h);l&&l.close();b=a}else b=_.Jk(c,b,f,e,d);return b};

_.u("gapi.iframes.create",_.Qk);
_.u("gadgets.json.stringify",_.jf);_.u("gadgets.json.parse",_.hf);
_.Uf=window.gapi&&window.gapi.util||{};
_.Wf=function(a){if(!a)return"";a=a.split("#")[0].split("?")[0];a=a.toLowerCase();0==a.indexOf("//")&&(a=window.location.protocol+a);/^[\w\-]*:\/\//.test(a)||(a=window.location.href);var b=a.substring(a.indexOf("://")+3),c=b.indexOf("/");-1!=c&&(b=b.substring(0,c));a=a.substring(0,a.indexOf("://"));if("http"!==a&&"https"!==a&&"chrome-extension"!==a&&"file"!==a&&"android-app"!==a&&"chrome-search"!==a&&"app"!==a)throw Error("w`"+a);c="";var d=b.indexOf(":");if(-1!=d){var e=b.substring(d+1);b=b.substring(0, d);if("http"===a&&"80"!==e||"https"===a&&"443"!==e)c=":"+e}return a+"://"+b+c};

_.Uf.Qa=function(a){return _.Wf(a)};
var ye;ye=window.console;_.ze=function(a){ye&&ye.log&&ye.log(a)};_.Ae=function(a){ye&&(ye.error?ye.error(a):ye.log&&ye.log(a))};_.Be=function(){};
_.G=_.G||{};
_.G=_.G||{};
(function(){var a=null;_.G.Ic=function(b){var c="undefined"===typeof b;if(null!==a&&c)return a;var d={};b=b||window.location.href;var e=b.indexOf("?"),f=b.indexOf("#");b=(-1===f?b.substr(e+1):[b.substr(e+1,f-e-1),"&",b.substr(f+1)].join("")).split("&");e=window.decodeURIComponent?window.decodeURIComponent:window.unescape;f=0;for(var h=b.length;f<h;++f){var k=b[f].indexOf("=");if(-1!==k){var l=b[f].substring(0,k);k=b[f].substring(k+1);k=k.replace(/\+/g," ");try{d[l]=e(k)}catch(n){}}}c&&(a=d);return d}; _.G.Ic()})();
_.u("gadgets.util.getUrlParameters",_.G.Ic);
_.de(_.Ud.location.href,"rpctoken")&&_.je(_.Vd,"unload",function(){});
var fi=function(){this.Bs={nL:Zh?"../"+Zh:null,dS:$h,yI:ai,Vca:bi,Du:ci,Cda:di};this.Me=_.Ud;this.aL=this.$R;this.MS=/MSIE\s*[0-8](\D|$)/.test(window.navigator.userAgent);if(this.Bs.nL){this.Me=this.Bs.yI(this.Me,this.Bs.nL);var a=this.Me.document,b=a.createElement("script");b.setAttribute("type","text/javascript");b.text="window.doPostMsg=function(w,s,o) {window.setTimeout(function(){w.postMessage(s,o);},0);};";a.body.appendChild(b);this.aL=this.Me.doPostMsg}this.ND={};this.lE={};a=(0,_.A)(this.LA,
this);_.je(this.Me,"message",a);_.Zd(_.ke,"RPMQ",[]).push(a);this.Me!=this.Me.parent&&ei(this,this.Me.parent,'{"h":"'+(0,window.escape)(this.Me.name)+'"}',"*")},gi=function(a){var b=null;0===a.indexOf('{"h":"')&&a.indexOf('"}')===a.length-2&&(b=(0,window.unescape)(a.substring(6,a.length-2)));return b},hi=function(a){if(!/^\s*{/.test(a))return!1;a=_.hf(a);return null!==a&&"object"===typeof a&&!!a.g};
fi.prototype.LA=function(a){var b=String(a.data);(0,_.Be)("gapi.rpc.receive("+bi+"): "+(!b||512>=b.length?b:b.substr(0,512)+"... ("+b.length+" bytes)"));var c=0!==b.indexOf("!_");c||(b=b.substring(2));var d=hi(b);if(!c&&!d){if(!d&&(c=gi(b))){if(this.ND[c])this.ND[c]();else this.lE[c]=1;return}var e=a.origin,f=this.Bs.dS;this.MS?_.Ud.setTimeout(function(){f(b,e)},0):f(b,e)}};fi.prototype.Fc=function(a,b){".."===a||this.lE[a]?(b(),delete this.lE[a]):this.ND[a]=b};
var ei=function(a,b,c,d){var e=hi(c)?"":"!_";(0,_.Be)("gapi.rpc.send("+bi+"): "+(!c||512>=c.length?c:c.substr(0,512)+"... ("+c.length+" bytes)"));a.aL(b,e+c,d)};fi.prototype.$R=function(a,b,c){a.postMessage(b,c)};fi.prototype.send=function(a,b,c){(a=this.Bs.yI(this.Me,a))&&!a.closed&&ei(this,a,b,c)};
var ii,ji,ki,li,mi,ni,oi,pi,Zh,bi,qi,ri,si,ti,ai,ci,ui,vi,Ai,Bi,Fi,di,Hi,Gi,wi,xi,Ii,$h,Mi,Ni;ii=0;ji=[];ki={};li={};mi=_.G.Ic;ni=mi();oi=ni.rpctoken;pi=ni.parent||_.Vd.referrer;Zh=ni.rly;bi=Zh||(_.Ud!==_.Ud.top||_.Ud.opener)&&_.Ud.name||"..";qi=null;ri={};si=function(){};ti={send:si,Fc:si};
ai=function(a,b){"/"==b.charAt(0)&&(b=b.substring(1),a=_.Ud.top);for(b=b.split("/");b.length;){var c=b.shift();"{"==c.charAt(0)&&"}"==c.charAt(c.length-1)&&(c=c.substring(1,c.length-1));if(".."===c)a=a==a.parent?a.opener:a.parent;else if(".."!==c&&a.frames[c]){if(a=a.frames[c],!("postMessage"in a))throw"Not a window";}else return null}return a};ci=function(a){return(a=ki[a])&&a.Kk};
ui=function(a){if(a.f in{})return!1;var b=a.t,c=ki[a.r];a=a.origin;return c&&(c.Kk===b||!c.Kk&&!b)&&(a===c.origin||"*"===c.origin)};vi=function(a){var b=a.id.split("/"),c=b[b.length-1],d=a.origin;return function(a){var b=a.origin;return a.f==c&&(d==b||"*"==d)}};_.yi=function(a,b,c){a=wi(a);li[a.name]={Sg:b,fr:a.fr,Mo:c||ui};xi()};_.zi=function(a){delete li[wi(a).name]};Ai={};Bi=function(a,b){(a=Ai["_"+a])&&a[1](this)&&a[0].call(this,b)};
Fi=function(a){var b=a.c;if(!b)return si;var c=a.r,d=a.g?"legacy__":"";return function(){var a=[].slice.call(arguments,0);a.unshift(c,d+"__cb",null,b);_.Ei.apply(null,a)}};di=function(a){qi=a};Hi=function(a){ri[a]||(ri[a]=_.Ud.setTimeout(function(){ri[a]=!1;Gi(a)},0))};Gi=function(a){var b=ki[a];if(b&&b.ready){var c=b.BC;for(b.BC=[];c.length;)ti.send(a,_.jf(c.shift()),b.origin)}};wi=function(a){return 0===a.indexOf("legacy__")?{name:a.substring(8),fr:!0}:{name:a,fr:!1}};
xi=function(){for(var a=_.C("rpc/residenceSec")||60,b=(new Date).getTime()/1E3,c=0,d;d=ji[c];++c){var e=d.xm;if(!e||0<a&&b-d.timestamp>a)ji.splice(c,1),--c;else{var f=e.s,h=li[f]||li["*"];if(h)if(ji.splice(c,1),--c,e.origin=d.origin,d=Fi(e),e.callback=d,h.Mo(e)){if("__cb"!==f&&!!h.fr!=!!e.g)break;e=h.Sg.apply(e,e.a);void 0!==e&&d(e)}else(0,_.Be)("gapi.rpc.rejected("+bi+"): "+f)}}};Ii=function(a,b,c){ji.push({xm:a,origin:b,timestamp:(new Date).getTime()/1E3});c||xi()};
$h=function(a,b){a=_.hf(a);Ii(a,b,!1)};Mi=function(a){for(;a.length;)Ii(a.shift(),this.origin,!0);xi()};Ni=function(a){var b=!1;a=a.split("|");var c=a[0];0<=c.indexOf("/")&&(b=!0);return{id:c,origin:a[1]||"*",qB:b}};
_.Oi=function(a,b,c,d){var e=Ni(a);d&&(_.Ud.frames[e.id]=_.Ud.frames[e.id]||d);a=e.id;if(!ki.hasOwnProperty(a)){c=c||null;d=e.origin;if(".."===a)d=_.Uf.Qa(pi),c=c||oi;else if(!e.qB){var f=_.Vd.getElementById(a);f&&(f=f.src,d=_.Uf.Qa(f),c=c||mi(f).rpctoken)}"*"===e.origin&&d||(d=e.origin);ki[a]={Kk:c,BC:[],origin:d,JZ:b,gL:function(){var b=a;ki[b].ready=1;Gi(b)}};ti.Fc(a,ki[a].gL)}return ki[a].gL};
_.Ei=function(a,b,c,d){a=a||"..";_.Oi(a);a=a.split("|",1)[0];var e=b,f=[].slice.call(arguments,3),h=c,k=bi,l=oi,n=ki[a],p=k,q=Ni(a);if(n&&".."!==a){if(q.qB){if(!(l=ki[a].JZ)){l=qi?qi.substring(1).split("/"):[bi];p=l.length-1;for(var t=_.Ud.parent;t!==_.Ud.top;){var v=t.parent;if(!p--){for(var w=null,y=v.frames.length,F=0;F<y;++F)v.frames[F]==t&&(w=F);l.unshift("{"+w+"}")}t=v}l="/"+l.join("/")}p=l}else p=k="..";l=n.Kk}h&&q?(n=ui,q.qB&&(n=vi(q)),Ai["_"+ ++ii]=[h,n],h=ii):h=null;f={s:e,f:k,r:p,t:l,c:h, a:f};e=wi(e);f.s=e.name;f.g=e.fr;ki[a].BC.push(f);Hi(a)};if("function"===typeof _.Ud.postMessage||"object"===typeof _.Ud.postMessage)ti=new fi,_.yi("__cb",Bi,function(){return!0}),_.yi("_processBatch",Mi,function(){return!0}),_.Oi("..");

_.Pi=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};_.Qi=function(a,b){a:{for(var c=a.length,d=_.r(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a)){b=e;break a}b=-1}return 0>b?null:_.r(a)?a.charAt(b):a[b]};_.Ri=[];_.Si=[];_.Ti=!1;_.Ui=function(a){_.Ri[_.Ri.length]=a;if(_.Ti)for(var b=0;b<_.Si.length;b++)a((0,_.A)(_.Si[b].wrap,_.Si[b]))};

var Vi,Wi,bj;Vi=null;Wi=/^[\w+/_-]+[=]{0,2}$/;_.Xi=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,_.Xi);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};_.x(_.Xi,Error);_.Xi.prototype.name="CustomError";_.Yi=function(a,b){for(var c in a)if(!(c in b)||a[c]!==b[c])return!1;for(c in b)if(!(c in a))return!1;return!0};_.Zi=function(a){var b={},c;for(c in a)b[c]=a[c];return b};_.$i=function(a){return a};
_.aj=function(a,b){a.src=_.Uc(b);if(null===Vi){a:{b=_.m.document;if((b=b.querySelector&&b.querySelector("script[nonce]"))&&(b=b.nonce||b.getAttribute("nonce"))&&Wi.test(b))break a;b=null}Vi=b||""}(b=Vi)&&a.setAttribute("nonce",b)};bj=function(a,b){this.VR=a;this.xZ=b;this.Nv=0;this.Ye=null};bj.prototype.get=function(){if(0<this.Nv){this.Nv--;var a=this.Ye;this.Ye=a.next;a.next=null}else a=this.VR();return a};bj.prototype.put=function(a){this.xZ(a);100>this.Nv&&(this.Nv++,a.next=this.Ye,this.Ye=a)};
var cj,ej,fj,dj;cj=function(a){_.m.setTimeout(function(){throw a;},0)};_.gj=function(a){a=dj(a);!_.bb(_.m.setImmediate)||_.m.Window&&_.m.Window.prototype&&!_.Bb("Edge")&&_.m.Window.prototype.setImmediate==_.m.setImmediate?(ej||(ej=fj()),ej(a)):_.m.setImmediate(a)};
fj=function(){var a=_.m.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!_.Bb("Presto")&&(a=function(){var a=window.document.createElement("IFRAME");a.style.display="none";a.src="";window.document.documentElement.appendChild(a);var b=a.contentWindow;a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host;a=(0,_.A)(function(a){if(("*"==
d||a.origin==d)&&a.data==c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&!_.Jb()){var b=new a,c={},d=c;b.port1.onmessage=function(){if(_.Ka(c.next)){c=c.next;var a=c.cb;c.cb=null;a()}};return function(a){d.next={cb:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof window.document&&"onreadystatechange"in window.document.createElement("SCRIPT")?function(a){var b=window.document.createElement("SCRIPT"); b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};window.document.documentElement.appendChild(b)}:function(a){_.m.setTimeout(a,0)}};dj=_.$i;_.Ui(function(a){dj=a});
var hj=function(){this.nx=this.Po=null},jj=new bj(function(){return new ij},function(a){a.reset()});hj.prototype.add=function(a,b){var c=jj.get();c.set(a,b);this.nx?this.nx.next=c:this.Po=c;this.nx=c};hj.prototype.remove=function(){var a=null;this.Po&&(a=this.Po,this.Po=this.Po.next,this.Po||(this.nx=null),a.next=null);return a};var ij=function(){this.next=this.scope=this.Sg=null};ij.prototype.set=function(a,b){this.Sg=a;this.scope=b;this.next=null}; ij.prototype.reset=function(){this.next=this.scope=this.Sg=null};
var kj,lj,mj,nj,pj;_.oj=function(a,b){kj||lj();mj||(kj(),mj=!0);nj.add(a,b)};lj=function(){if(_.m.Promise&&_.m.Promise.resolve){var a=_.m.Promise.resolve(void 0);kj=function(){a.then(pj)}}else kj=function(){_.gj(pj)}};mj=!1;nj=new hj;pj=function(){for(var a;a=nj.remove();){try{a.Sg.call(a.scope)}catch(b){cj(b)}jj.put(a)}mj=!1};
_.qj=function(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0};_.rj=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};var tj,uj,Ej,Cj;_.sj=function(a,b){this.Fa=0;this.aj=void 0;this.bn=this.Lj=this.hb=null;this.Gu=this.Dz=!1;if(a!=_.Xa)try{var c=this;a.call(b,function(a){c.fh(2,a)},function(a){c.fh(3,a)})}catch(d){this.fh(3,d)}};tj=function(){this.next=this.context=this.Yn=this.wr=this.$k=null;this.mp=!1};tj.prototype.reset=function(){this.context=this.Yn=this.wr=this.$k=null;this.mp=!1};uj=new bj(function(){return new tj},function(a){a.reset()});_.vj=function(a,b,c){var d=uj.get();d.wr=a;d.Yn=b;d.context=c;return d};
_.wj=function(a){if(a instanceof _.sj)return a;var b=new _.sj(_.Xa);b.fh(2,a);return b};_.xj=function(a){return new _.sj(function(b,c){c(a)})};_.zj=function(a,b,c){yj(a,b,c,null)||_.oj(_.Pi(b,a))};_.Bj=function(){var a,b,c=new _.sj(function(c,e){a=c;b=e});return new Aj(c,a,b)};_.sj.prototype.then=function(a,b,c){return Cj(this,_.bb(a)?a:null,_.bb(b)?b:null,c)};_.qj(_.sj);_.sj.prototype.eE=function(a,b){return Cj(this,null,a,b)};
_.sj.prototype.cancel=function(a){0==this.Fa&&_.oj(function(){var b=new Dj(a);Ej(this,b)},this)};Ej=function(a,b){if(0==a.Fa)if(a.hb){var c=a.hb;if(c.Lj){for(var d=0,e=null,f=null,h=c.Lj;h&&(h.mp||(d++,h.$k==a&&(e=h),!(e&&1<d)));h=h.next)e||(f=h);e&&(0==c.Fa&&1==d?Ej(c,b):(f?(d=f,d.next==c.bn&&(c.bn=d),d.next=d.next.next):Fj(c),Gj(c,e,3,b)))}a.hb=null}else a.fh(3,b)};_.Ij=function(a,b){a.Lj||2!=a.Fa&&3!=a.Fa||Hj(a);a.bn?a.bn.next=b:a.Lj=b;a.bn=b};
Cj=function(a,b,c,d){var e=_.vj(null,null,null);e.$k=new _.sj(function(a,h){e.wr=b?function(c){try{var e=b.call(d,c);a(e)}catch(n){h(n)}}:a;e.Yn=c?function(b){try{var e=c.call(d,b);!_.Ka(e)&&b instanceof Dj?h(b):a(e)}catch(n){h(n)}}:h});e.$k.hb=a;_.Ij(a,e);return e.$k};_.sj.prototype.M0=function(a){this.Fa=0;this.fh(2,a)};_.sj.prototype.N0=function(a){this.Fa=0;this.fh(3,a)};
_.sj.prototype.fh=function(a,b){0==this.Fa&&(this===b&&(a=3,b=new TypeError("Promise cannot resolve to itself")),this.Fa=1,yj(b,this.M0,this.N0,this)||(this.aj=b,this.Fa=a,this.hb=null,Hj(this),3!=a||b instanceof Dj||Jj(this,b)))};
var yj=function(a,b,c,d){if(a instanceof _.sj)return _.Ij(a,_.vj(b||_.Xa,c||null,d)),!0;if(_.rj(a))return a.then(b,c,d),!0;if(_.ab(a))try{var e=a.then;if(_.bb(e))return Kj(a,e,b,c,d),!0}catch(f){return c.call(d,f),!0}return!1},Kj=function(a,b,c,d,e){var f=!1,h=function(a){f||(f=!0,c.call(e,a))},k=function(a){f||(f=!0,d.call(e,a))};try{b.call(a,h,k)}catch(l){k(l)}},Hj=function(a){a.Dz||(a.Dz=!0,_.oj(a.vS,a))},Fj=function(a){var b=null;a.Lj&&(b=a.Lj,a.Lj=b.next,b.next=null);a.Lj||(a.bn=null);return b};
_.sj.prototype.vS=function(){for(var a;a=Fj(this);)Gj(this,a,this.Fa,this.aj);this.Dz=!1};var Gj=function(a,b,c,d){if(3==c&&b.Yn&&!b.mp)for(;a&&a.Gu;a=a.hb)a.Gu=!1;if(b.$k)b.$k.hb=null,Lj(b,c,d);else try{b.mp?b.wr.call(b.context):Lj(b,c,d)}catch(e){Mj.call(null,e)}uj.put(b)},Lj=function(a,b,c){2==b?a.wr.call(a.context,c):a.Yn&&a.Yn.call(a.context,c)},Jj=function(a,b){a.Gu=!0;_.oj(function(){a.Gu&&Mj.call(null,b)})},Mj=cj,Dj=function(a){_.Xi.call(this,a)};_.x(Dj,_.Xi);Dj.prototype.name="cancel"; var Aj=function(a,b,c){this.promise=a;this.resolve=b;this.reject=c};

_.Nj=function(a){return new _.sj(a)};
_.Oj=_.Oj||{};_.Oj.GU=function(){var a=0,b=0;window.self.innerHeight?(a=window.self.innerWidth,b=window.self.innerHeight):window.document.documentElement&&window.document.documentElement.clientHeight?(a=window.document.documentElement.clientWidth,b=window.document.documentElement.clientHeight):window.document.body&&(a=window.document.body.clientWidth,b=window.document.body.clientHeight);return{width:a,height:b}};

_.Oj=_.Oj||{};
(function(){function a(a,c){window.getComputedStyle(a,"").getPropertyValue(c).match(/^([0-9]+)/);return(0,window.parseInt)(RegExp.$1,10)}_.Oj.Zc=function(){var b=_.Oj.GU().height,c=window.document.body,d=window.document.documentElement;if("CSS1Compat"===window.document.compatMode&&d.scrollHeight)return d.scrollHeight!==b?d.scrollHeight:d.offsetHeight;if(0<=window.navigator.userAgent.indexOf("AppleWebKit")){b=0;for(c=[window.document.body];0<c.length;){var e=c.shift();d=e.childNodes;if("undefined"!==
typeof e.style){var f=e.style.overflowY;f||(f=(f=window.document.defaultView.getComputedStyle(e,null))?f.overflowY:null);if("visible"!=f&&"inherit"!=f&&(f=e.style.height,f||(f=(f=window.document.defaultView.getComputedStyle(e,null))?f.height:""),0<f.length&&"auto"!=f))continue}for(e=0;e<d.length;e++){f=d[e];if("undefined"!==typeof f.offsetTop&&"undefined"!==typeof f.offsetHeight){var h=f.offsetTop+f.offsetHeight+a(f,"margin-bottom");b=Math.max(b,h)}c.push(f)}}return b+a(window.document.body,"border-bottom")+ a(window.document.body,"margin-bottom")+a(window.document.body,"padding-bottom")}if(c&&d)return e=d.scrollHeight,f=d.offsetHeight,d.clientHeight!==f&&(e=c.scrollHeight,f=c.offsetHeight),e>b?e>f?e:f:e<f?e:f}})();

_.Rk=function(a){this.R=a};_.g=_.Rk.prototype;_.g.value=function(){return this.R};_.g.nj=function(a){this.R.width=a;return this};_.g.Fd=function(){return this.R.width};_.g.kj=function(a){this.R.height=a;return this};_.g.Zc=function(){return this.R.height};_.g.ld=function(a){this.R.style=a;return this};_.g.Ll=_.ca(5);
var Sk=function(a){this.R=a};Sk.prototype.Ao=function(a){this.R.anchor=a;return this};Sk.prototype.Af=function(){return this.R.anchor};Sk.prototype.iD=function(a){this.R.anchorPosition=a;return this};_.Tk=function(a){a.R.show=!0;return a};Sk.prototype.kj=function(a){this.R.height=a;return this};Sk.prototype.Zc=function(){return this.R.height};Sk.prototype.nj=function(a){this.R.width=a;return this};Sk.prototype.Fd=function(){return this.R.width};
_.Uk=function(a){this.R=a||{}};_.Uk.prototype.value=function(){return this.R};_.Uk.prototype.setUrl=function(a){this.R.url=a;return this};_.Uk.prototype.getUrl=function(){return this.R.url};_.Vk=function(a,b){a.R.where=b;return a};_.g=_.Uk.prototype;_.g.ld=function(a){this.R.style=a;return this};_.g.Ll=_.ca(4);_.g.Ie=function(a){this.R.id=a;return this};_.g.ka=function(){return this.R.id};_.g.Ek=_.ca(6);_.Wk=function(a,b){a.R.queryParams=b;return a};_.Xk=function(a,b){a.R.relayOpen=b;return a};
_.Yk=function(a,b){a.R.messageHandlers=b;return a};_.Zk=function(a,b){a.R.messageHandlersFilter=b;return a};_.Uk.prototype.Bo=_.ca(7);_.Uk.prototype.getContext=function(){return this.R.context};_.Uk.prototype.Pc=function(){return this.R.openerIframe};_.$k=function(a){return new Sk(a.R)};_.Uk.prototype.Bl=function(){this.R.attributes=this.R.attributes||{};return new _.Rk(this.R.attributes)};_.al=function(a){a.R.connectWithQueryParams=!0;return a};

var bl,fl,gl,hl,nl,ml;_.Rk.prototype.Ll=_.oc(5,function(){return this.R.style});_.Uk.prototype.Ll=_.oc(4,function(){return this.R.style});bl=function(a,b){a.R.onload=b};_.cl=function(a){a.R.closeClickDetection=!0};_.dl=function(a){return a.R.rpctoken};_.el=function(a){a.R.waitForOnload=!0;return a};fl=function(a){return(a=a.R.timeout)?a:null};_.jl=function(a,b,c){if(a){_.dk(_.bk(a),"arrayForEach was called with a non array value");for(var d=0;d<a.length;d++)b.call(c,a[d],d)}};
_.kl=function(a,b,c){if(a)if(_.bk(a))_.jl(a,b,c);else{_.dk("object"===typeof a,"objectForEach was called with a non object value");c=c||a;for(var d in a)_.ae(a,d)&&void 0!==a[d]&&b.call(c,a[d],d)}};_.ll=function(a){return new _.sj(function(b,c){var d=a.length,e=[];if(d)for(var f=function(a,c){d--;e[a]=c;0==d&&b(e)},h=function(a){c(a)},k=0,l;k<a.length;k++)l=a[k],_.zj(l,_.Pi(f,k),h);else b(e)})}; nl=function(a){this.resolve=this.reject=null;this.promise=_.Nj((0,_.A)(function(a,c){this.resolve=a;this.reject=c},this));a&&(this.promise=ml(this.promise,a))};ml=function(a,b){return a.then(function(a){try{b(a)}catch(d){}return a})};
_.ol=function(a){this.R=a||{}};_.x(_.ol,_.Uk);_.pl=function(a,b){a.R.frameName=b;return a};_.ol.prototype.Cd=function(){return this.R.frameName};_.ql=function(a,b){a.R.rpcAddr=b;return a};_.ol.prototype.Jl=function(){return this.R.rpcAddr};_.rl=function(a,b){a.R.retAddr=b;return a};_.sl=function(a){return a.R.retAddr};_.ol.prototype.Uh=function(a){this.R.origin=a;return this};_.ol.prototype.Qa=function(){return this.R.origin};_.ol.prototype.lj=function(a){this.R.setRpcReady=a;return this};_.tl=function(a){return a.R.setRpcReady}; _.ol.prototype.Do=function(a){this.R.context=a};var ul=function(a,b){a.R._rpcReadyFn=b};_.ol.prototype.Ga=function(){return this.R.iframeEl};
var vl,zl,yl;vl=/^[\w\.\-]*$/;_.wl=function(a){return a.Rc===a.getContext().Rc};_.K=function(){return!0};_.xl=function(a){for(var b=_.$d(),c=0;c<a.length;c++)b[a[c]]=!0;return function(a){return!!b[a.Rc]}};zl=function(a,b,c){return function(d){if(!b.Hb){_.dk(this.origin===b.Rc,"Wrong origin "+this.origin+" != "+b.Rc);var e=this.callback;d=yl(a,d,b);!c&&0<d.length&&_.ll(d).then(e)}}};yl=function(a,b,c){a=gl[a];if(!a)return[];for(var d=[],e=0;e<a.length;e++)d.push(_.wj(a[e].call(c,b,c)));return d};
_.Al=function(a,b,c){_.dk("_default"!=a,"Cannot update default api");hl[a]={map:b,filter:c}};_.Bl=function(a,b,c){_.dk("_default"!=a,"Cannot update default api");_.Zd(hl,a,{map:{},filter:_.wl}).map[b]=c};_.Cl=function(a,b){_.Zd(hl,"_default",{map:{},filter:_.K}).map[a]=b;_.kl(_.il.Pe,function(c){c.register(a,b,_.K)})};_.Dl=function(){return _.il};
_.Fl=function(a){a=a||{};this.Hb=!1;this.VK=_.$d();this.Pe=_.$d();this.Me=a._window||_.Ud;this.Tc=this.Me.location.href;this.WK=(this.nC=El(this.Tc,"parent"))?El(this.Tc,"pfname"):"";this.Aa=this.nC?El(this.Tc,"_gfid")||El(this.Tc,"id"):"";this.zf=_.Gk(this.Aa,this.WK);this.Rc=_.Uf.Qa(this.Tc);if(this.Aa){var b=new _.ol;_.ql(b,a._parentRpcAddr||"..");_.rl(b,a._parentRetAddr||this.Aa);b.Uh(_.Uf.Qa(this.nC||this.Tc));_.pl(b,this.WK);this.hb=this.Hj(b.value())}else this.hb=null};_.g=_.Fl.prototype;
_.g.Nn=_.ca(9);_.g.Ca=function(){if(!this.Hb){for(var a=0;a<this.Pe.length;a++)this.Pe[a].Ca();this.Hb=!0}};_.g.Cd=function(){return this.zf};_.g.wb=function(){return this.Me};_.g.tb=function(){return this.Me.document};_.g.Kw=_.ca(10);_.g.eA=function(a){return this.VK[a]};
_.g.Hj=function(a){_.dk(!this.Hb,"Cannot attach iframe in disposed context");a=new _.ol(a);a.Jl()||_.ql(a,a.ka());_.sl(a)||_.rl(a,"..");a.Qa()||a.Uh(_.Uf.Qa(a.getUrl()));a.Cd()||_.pl(a,_.Gk(a.ka(),this.zf));var b=a.Cd();if(this.Pe[b])return this.Pe[b];var c=a.Jl(),d=c;a.Qa()&&(d=c+"|"+a.Qa());var e=_.sl(a),f=_.dl(a);f||(f=(f=a.Ga())&&(f.getAttribute("data-postorigin")||f.src)||a.getUrl(),f=_.de(f,"rpctoken"));ul(a,_.Oi(d,e,f,a.R._popupWindow));d=((window.gadgets||{}).rpc||{}).setAuthToken;f&&d&&d(c,
f);var h=new _.Gl(this,c,b,a),k=a.R.messageHandlersFilter;_.kl(a.R.messageHandlers,function(a,b){h.register(b,a,k)});_.tl(a)&&h.lj();_.Hl(h,"_g_rpcReady");return h};_.g.TC=function(a){_.pl(a,null);var b=a.ka();!b||vl.test(b)&&!this.wb().document.getElementById(b)||(_.ze("Ignoring requested iframe ID - "+b),a.Ie(null))};var El=function(a,b){var c=_.de(a,b);c||(c=_.hf(_.de(a,"jcp",""))[b]);return c||""};
_.Fl.prototype.Ph=function(a){_.dk(!this.Hb,"Cannot open iframe in disposed context");var b=new _.ol(a);Il(this,b);var c=b.Cd();if(c&&this.Pe[c])return this.Pe[c];this.TC(b);c=b.getUrl();_.dk(c,"No url for new iframe");var d=b.R.queryParams||{};d.usegapi="1";_.Wk(b,d);d=this.TI&&this.TI(c,b);d||(d=b.R.where,_.dk(!!d,"No location for new iframe"),c=_.Qk(c,d,a),b.R.iframeEl=c,d=c.getAttribute("id"));_.ql(b,d).Ie(d);b.Uh(_.Uf.Qa(b.R.eurl||""));this.aK&&this.aK(b,b.Ga());c=this.Hj(a);c.DD&&c.DD(c,a);
(a=b.R.onCreate)&&a(c);b.R.disableRelayOpen||c.qp("_open");return c};
var Jl=function(a,b,c){var d=b.R.canvasUrl;if(!d)return c;_.dk(!b.R.allowPost&&!b.R.forcePost,"Post is not supported when using canvas url");var e=b.getUrl();_.dk(e&&_.Uf.Qa(e)===a.Rc&&_.Uf.Qa(d)===a.Rc,"Wrong origin for canvas or hidden url "+d);b.setUrl(d);_.el(b);b.R.canvasUrl=null;return function(a){var b=a.wb(),d=b.location.hash;d=_.Pk(e)+(/#/.test(e)?d.replace(/^#/,"&"):d);b.location.replace(d);c&&c(a)}},Ll=function(a,b,c){var d=b.R.relayOpen;if(d){var e=a.hb;d instanceof _.Gl?(e=d,_.Xk(b,0)):
0<Number(d)&&_.Xk(b,Number(d)-1);if(e){_.dk(!!e.NK,"Relaying iframe open is disabled");if(d=b.Ll())if(d=_.Kl[d])b.Do(a),d(b.value()),b.Do(null);b.R.openerIframe=null;c.resolve(e.NK(b));return!0}}return!1},Pl=function(a,b,c){var d=b.Ll();if(d)if(_.dk(!!_.Ml,"Defer style is disabled, when requesting style "+d),_.Nl[d])Il(a,b);else return Ol(d,function(){_.dk(!!_.Nl[d],"Fail to load style - "+d);c.resolve(a.open(b.value()))}),!0;return!1};
_.Fl.prototype.open=function(a,b){_.dk(!this.Hb,"Cannot open iframe in disposed context");var c=new _.ol(a);b=Jl(this,c,b);var d=new nl(b);(b=c.getUrl())&&c.setUrl(_.Pk(b));if(Ll(this,c,d)||Pl(this,c,d)||Ll(this,c,d))return d.promise;if(null!=fl(c)){var e=(0,window.setTimeout)(function(){h.Ga().src="about:blank";d.reject({timeout:"Exceeded time limit of :"+fl(c)+"milliseconds"})},fl(c)),f=d.resolve;d.resolve=function(a){(0,window.clearTimeout)(e);f(a)}}c.R.waitForOnload&&bl(c.Bl(),function(){d.resolve(h)});
var h=this.Ph(a);c.R.waitForOnload||d.resolve(h);return d.promise};_.Fl.prototype.iI=_.ca(11);_.Gl=function(a,b,c,d){this.Hb=!1;this.Rd=a;this.bj=b;this.zf=c;this.ya=d;this.ro=_.sl(this.ya);this.Rc=this.ya.Qa();this.yW=this.ya.Ga();this.MM=this.ya.R.where;this.fo=[];this.qp("_default");a=this.ya.R.apis||[];for(b=0;b<a.length;b++)this.qp(a[b]);this.Rd.Pe[c]=this};_.g=_.Gl.prototype;_.g.Nn=_.ca(8);
_.g.Ca=function(){if(!this.Hb){for(var a=0;a<this.fo.length;a++)this.unregister(this.fo[a]);delete _.il.Pe[this.Cd()];this.Hb=!0}};_.g.getContext=function(){return this.Rd};_.g.Jl=function(){return this.bj};_.g.Cd=function(){return this.zf};_.g.Ga=function(){return this.yW};_.g.$a=function(){return this.MM};_.g.kf=function(a){this.MM=a};_.g.lj=function(){(0,this.ya.R._rpcReadyFn)()};_.g.mM=function(a,b){this.ya.value()[a]=b};_.g.oA=function(a){return this.ya.value()[a]};_.g.Pb=function(){return this.ya.value()};
_.g.ka=function(){return this.ya.ka()};_.g.Qa=function(){return this.Rc};_.g.register=function(a,b,c){_.dk(!this.Hb,"Cannot register handler on disposed iframe "+a);_.dk((c||_.wl)(this),"Rejecting untrusted message "+a);c=this.zf+":"+this.Rd.zf+":"+a;1==_.Zd(gl,c,[]).push(b)&&(this.fo.push(a),_.yi(c,zl(c,this,"_g_wasClosed"===a)))};
_.g.unregister=function(a,b){var c=this.zf+":"+this.Rd.zf+":"+a,d=gl[c];d&&(b?(b=_.ck.call(d,b),0<=b&&d.splice(b,1)):d.splice(0,d.length),0==d.length&&(b=_.ck.call(this.fo,a),0<=b&&this.fo.splice(b,1),_.zi(c)))};_.g.pU=function(){return this.fo};_.g.qp=function(a){this.fy=this.fy||[];if(!(0<=_.ck.call(this.fy,a))){this.fy.push(a);a=hl[a]||{map:{}};for(var b in a.map)_.ae(a.map,b)&&this.register(b,a.map[b],a.filter)}};
_.g.send=function(a,b,c,d){_.dk(!this.Hb,"Cannot send message to disposed iframe - "+a);_.dk((d||_.wl)(this),"Wrong target for message "+a);c=new nl(c);_.Ei(this.bj,this.Rd.zf+":"+this.zf+":"+a,c.resolve,b);return c.promise};_.Hl=function(a,b,c,d){return a.send(b,c,d,_.K)};_.Gl.prototype.IY=function(a){return a};_.Gl.prototype.ping=function(a,b){return _.Hl(this,"_g_ping",b,a)};gl=_.$d();hl=_.$d();_.il=new _.Fl;_.Cl("_g_rpcReady",_.Gl.prototype.lj);_.Cl("_g_discover",_.Gl.prototype.pU); _.Cl("_g_ping",_.Gl.prototype.IY);
var Ol,Il;_.Nl=_.$d();_.Kl=_.$d();_.Ml=function(a){return _.Nl[a]};Ol=function(a,b){_.ce.load("gapi.iframes.style."+a,b)};Il=function(a,b){var c=b.Ll();if(c){b.ld(null);var d=_.Nl[c];_.dk(d,"No such style: "+c);b.Do(a);d(b.value());b.Do(null)}};var Ql,Rl;Ql={height:!0,width:!0};Rl=/^(?!-*(?:expression|(?:moz-)?binding))(?:[.#]?-?(?:[_a-z0-9-]+)(?:-[_a-z0-9-]+)*-?|-?(?:[0-9]+(?:\.[0-9]*)?|\.[0-9]+)(?:[a-z]{1,2}|%)?|!important|)$/i;_.Sl=function(a){"number"===typeof a&&(a=String(a)+"px");return a};_.Gl.prototype.wb=function(){if(!_.wl(this))return null;var a=this.ya.R._popupWindow;if(a)return a;var b=this.bj.split("/");a=this.getContext().wb();for(var c=0;c<b.length&&a;c++){var d=b[c];a=".."===d?a==a.parent?a.opener:a.parent:a.frames[d]}return a};
var Tl=function(a,b){var c=a.hb,d=!0;b.filter&&(d=b.filter.call(b.Df,b.params));return _.wj(d).then(function(d){return d&&c?(b.UK&&b.UK.call(a,b.params),d=b.sender?b.sender(b.params):_.Hl(c,b.message,b.params),b.e1?d.then(function(){return!0}):!0):!1})};
_.Fl.prototype.Fy=function(a,b,c){a=Tl(this,{sender:function(a){var b=_.il.hb;_.kl(_.il.Pe,function(c){c!==b&&_.Hl(c,"_g_wasClosed",a)});return _.Hl(b,"_g_closeMe",a)},message:"_g_closeMe",params:a,Df:c,filter:this.eA("onCloseSelfFilter")});b=new nl(b);b.resolve(a);return b.promise};_.Fl.prototype.QC=function(a,b,c){a=a||{};b=new nl(b);b.resolve(Tl(this,{message:"_g_restyleMe",params:a,Df:c,filter:this.eA("onRestyleSelfFilter"),e1:!0,UK:this.nN}));return b.promise};
_.Fl.prototype.nN=function(a){"auto"===a.height&&(a.height=_.Oj.Zc())};_.Ul=function(a){var b={};if(a)for(var c in a)_.ae(a,c)&&_.ae(Ql,c)&&Rl.test(a[c])&&(b[c]=a[c]);return b};_.g=_.Gl.prototype;_.g.close=function(a,b){return _.Hl(this,"_g_close",a,b)};_.g.Lr=function(a,b){return _.Hl(this,"_g_restyle",a,b)};_.g.oo=function(a,b){return _.Hl(this,"_g_restyleDone",a,b)};_.g.FR=function(a){return this.getContext().Fy(a,void 0,this)};
_.g.FZ=function(a){if(a&&"object"===typeof a)return this.getContext().QC(a,void 0,this)};_.g.GZ=function(a){var b=this.ya.R.onRestyle;b&&b.call(this,a,this);a=a&&"object"===typeof a?_.Ul(a):{};(b=this.Ga())&&a&&"object"===typeof a&&(_.ae(a,"height")&&(a.height=_.Sl(a.height)),_.ae(a,"width")&&(a.width=_.Sl(a.width)),_.be(a,b.style))};
_.g.GR=function(a){var b=this.ya.R.onClose;b&&b.call(this,a,this);this.LG&&this.LG()||(b=this.Ga())&&b.parentNode&&b.parentNode.removeChild(b);if(b=this.ya.R.controller){var c={};c.frameName=this.Cd();_.Hl(b,"_g_disposeControl",c)}yl(this.zf+":"+this.Rd.zf+":_g_wasClosed",a,this)};_.Fl.prototype.WL=_.ca(12);_.Fl.prototype.pM=_.ca(13);_.Gl.prototype.mL=_.ca(14);_.Gl.prototype.wk=function(a,b){this.register("_g_wasClosed",a,b)};
_.Gl.prototype.h1=function(){delete this.getContext().Pe[this.Cd()];this.getContext().wb().setTimeout((0,_.A)(function(){this.Ca()},this),0)};_.Cl("_g_close",_.Gl.prototype.FR);_.Cl("_g_closeMe",_.Gl.prototype.GR);_.Cl("_g_restyle",_.Gl.prototype.FZ);_.Cl("_g_restyleMe",_.Gl.prototype.GZ);_.Cl("_g_wasClosed",_.Gl.prototype.h1);

_.Gl.prototype.mL=_.oc(14,function(a,b){this.register("_g_wasRestyled",a,b)});_.g=_.Fl.prototype;_.g.pM=_.oc(13,function(a){this.Kw("onRestyleSelfFilter",a)});_.g.WL=_.oc(12,function(a){this.Kw("onCloseSelfFilter",a)});_.g.iI=_.oc(11,function(){return this.hb});_.g.Kw=_.oc(10,function(a,b){this.VK[a]=b});_.g.Nn=_.oc(9,function(){return this.Hb});_.Gl.prototype.Nn=_.oc(8,function(){return this.Hb});_.u("gapi.iframes.registerStyle",function(a,b){_.Nl[a]=b});
_.u("gapi.iframes.registerBeforeOpenStyle",function(a,b){_.Kl[a]=b});_.u("gapi.iframes.getStyle",_.Ml);_.u("gapi.iframes.getBeforeOpenStyle",function(a){return _.Kl[a]});_.u("gapi.iframes.registerIframesApi",_.Al);_.u("gapi.iframes.registerIframesApiHandler",_.Bl);_.u("gapi.iframes.getContext",_.Dl);_.u("gapi.iframes.SAME_ORIGIN_IFRAMES_FILTER",_.wl);_.u("gapi.iframes.CROSS_ORIGIN_IFRAMES_FILTER",_.K);_.u("gapi.iframes.makeWhiteListIframesFilter",_.xl);_.u("gapi.iframes.Context",_.Fl);
_.u("gapi.iframes.Context.prototype.isDisposed",_.Fl.prototype.Nn);_.u("gapi.iframes.Context.prototype.getWindow",_.Fl.prototype.wb);_.u("gapi.iframes.Context.prototype.getFrameName",_.Fl.prototype.Cd);_.u("gapi.iframes.Context.prototype.getGlobalParam",_.Fl.prototype.eA);_.u("gapi.iframes.Context.prototype.setGlobalParam",_.Fl.prototype.Kw);_.u("gapi.iframes.Context.prototype.open",_.Fl.prototype.open);_.u("gapi.iframes.Context.prototype.openChild",_.Fl.prototype.Ph);
_.u("gapi.iframes.Context.prototype.getParentIframe",_.Fl.prototype.iI);_.u("gapi.iframes.Context.prototype.closeSelf",_.Fl.prototype.Fy);_.u("gapi.iframes.Context.prototype.restyleSelf",_.Fl.prototype.QC);_.u("gapi.iframes.Context.prototype.setCloseSelfFilter",_.Fl.prototype.WL);_.u("gapi.iframes.Context.prototype.setRestyleSelfFilter",_.Fl.prototype.pM);_.u("gapi.iframes.Iframe",_.Gl);_.u("gapi.iframes.Iframe.prototype.isDisposed",_.Gl.prototype.Nn);
_.u("gapi.iframes.Iframe.prototype.getContext",_.Gl.prototype.getContext);_.u("gapi.iframes.Iframe.prototype.getFrameName",_.Gl.prototype.Cd);_.u("gapi.iframes.Iframe.prototype.getId",_.Gl.prototype.ka);_.u("gapi.iframes.Iframe.prototype.register",_.Gl.prototype.register);_.u("gapi.iframes.Iframe.prototype.unregister",_.Gl.prototype.unregister);_.u("gapi.iframes.Iframe.prototype.send",_.Gl.prototype.send);_.u("gapi.iframes.Iframe.prototype.applyIframesApi",_.Gl.prototype.qp);
_.u("gapi.iframes.Iframe.prototype.getIframeEl",_.Gl.prototype.Ga);_.u("gapi.iframes.Iframe.prototype.getSiteEl",_.Gl.prototype.$a);_.u("gapi.iframes.Iframe.prototype.setSiteEl",_.Gl.prototype.kf);_.u("gapi.iframes.Iframe.prototype.getWindow",_.Gl.prototype.wb);_.u("gapi.iframes.Iframe.prototype.getOrigin",_.Gl.prototype.Qa);_.u("gapi.iframes.Iframe.prototype.close",_.Gl.prototype.close);_.u("gapi.iframes.Iframe.prototype.restyle",_.Gl.prototype.Lr);
_.u("gapi.iframes.Iframe.prototype.restyleDone",_.Gl.prototype.oo);_.u("gapi.iframes.Iframe.prototype.registerWasRestyled",_.Gl.prototype.mL);_.u("gapi.iframes.Iframe.prototype.registerWasClosed",_.Gl.prototype.wk);_.u("gapi.iframes.Iframe.prototype.getParam",_.Gl.prototype.oA);_.u("gapi.iframes.Iframe.prototype.setParam",_.Gl.prototype.mM);_.u("gapi.iframes.Iframe.prototype.ping",_.Gl.prototype.ping);

});
// Google Inc.
